### ISSUE TITLE
Help with Professor Prebid on Site

### ISSUE THREAD

**Issue by lewisalee-rea-group** [prebid/professor-prebid#100]
### Type of issue
Professor Prebid not working on site, with no bids being shown through the extension and no Prebid detected

### Description
Professor Prebid is not working specifically on below site:
https://www.realestate.com.au/buy/in-lugarno,+nsw+2210/list-1

### Steps to reproduce
just connect to https://www.realestate.com.au/buy/in-lugarno,+nsw+2210/list-1

### Test page
https://www.realestate.com.au/buy/in-lugarno,+nsw+2210/list-1

### Expected results
Prebid should be detected within the page, however Professor Prebid isnt able to detect this

### Actual results
No prebid detected on the page

### Platform details
Any browser.

### Other information

**Comment by florianerl** [comment]
Hi @lewisalee-rea-group , 

thanks for your feedback! I pushed an update last night that should fix your problem: 
![845CB74D-8851-4DF0-B6D5-8C0C3F76E16A-716-00005ADB568614E8](https://github.com/prebid/professor-prebid/assets/46747754/ea619a18-b09d-4009-92c7-b522dad378a1)

Please let me know if you still encounter issues! 🙏

**Comment by lewisalee-rea-group** [comment]
Thanks Florian! Everything appears to be working now.

Cheers,

Lewis Lee | Senior AdTech Specialist | REA Group | ***@***.******@***.***> | +61 436 527 227<tel:+61436527227> | L17, 309 Kent St, Sydney, 2000 | Zoom: 979 062 1745

From: Florian Erl ***@***.***>
Date: Saturday, 29 June 2024 at 12:44 am
To: prebid/professor-prebid ***@***.***>
Cc: Lewis Lee ***@***.***>, Mention ***@***.***>
Subject: Re: [prebid/professor-prebid] Help with Professor Prebid on Site (Issue #100)
[External Email]


Hi @lewisalee-rea-group<https://github.com/lewisalee-rea-group> ,

thanks for your feedback! I pushed an update last night that should fix your problem:
845CB74D-8851-4DF0-B6D5-8C0C3F76E16A-716-00005ADB568614E8.gif (view on web)<https://github.com/prebid/professor-prebid/assets/46747754/ea619a18-b09d-4009-92c7-b522dad378a1>

Please let me know if you still encounter issues! 🙏
