### ISSUE TITLE
Cloudflare Turnstile doesn't work with this extension

### ISSUE THREAD

**Issue by dimention** [prebid/professor-prebid#109]
For some reason this extension is causing Cloudflare Turnstile (Captha) to stop working thus limiting access to Cloudflare's dashboard and a broad list of sites using it.

This is happening with 0.2.75 version.

**Reproduce**
Install Professor Prebid, go to https://dash.cloudflare.com/login
The Cloudflare Turnstile keeps reloading

**Comment by florianerl** [comment]
Hi @dimention , 

thanks for raising this. I "fixed" the issue by excluding "challenges.cloudflare.com" here: https://github.com/prebid/professor-prebid/blob/1b5d157c3f793ed80ba5780c74fdf8d5a41b5635/src/pages/Content/index.ts#L12

i just uploaded the new version (0.2.76) to cws for approval
