### ISSUE TITLE
Site styles can still override overlay styles

### ISSUE THREAD

**Issue by timothyasp** [prebid/professor-prebid#18]
https://d.pr/i/NVYBv2

https://markets.businessinsider.com/news/stocks/big-short-michael-burry-stock-market-plane-crash-housing-bubble-2022-5?utm_source=reddit.com

My suggestion would to just go nuclear and stick `!important` for all styles on the overlay elements.

**Comment by florianerl** [comment]
Hi @timothyasp , 

i have pushed some changes to the attached branch trying a less nuclear way by encapsulating the overlays in iframes. ☮️  😄 . let me know if that works for you.
