### ISSUE TITLE
gam links broken for mcm pubs

### ISSUE THREAD

**Issue by patmmccann** [prebid/professor-prebid#25]
Going to https://firstquarterfinance.com/, one sees for example: 

https://admanager.google.com/18190176,22497559205#delivery/LineItemDetail/lineItemId=604570136

should be

https://admanager.google.com/18190176#delivery/LineItemDetail/lineItemId=604570136

Same problem at 

https://dinnerthendessert.com/cinnamon-roll-monkey-bread/
https://admanager.google.com/1030006,22613210658#delivery/LineItemDetail/lineItemId=5219256474
should be 
https://admanager.google.com/1030006#delivery/LineItemDetail/lineItemId=5219256474

**Comment by florianerl** [comment]
hi @patmmccann , 

the issue should be fixed with the latest version. Please let me know in case it isn't.

**Comment by patmmccann** [comment]
I am running 0.2.45
It seems to be fixed for query id but not lineitem id. What version is the fix in?

**Comment by patmmccann** [comment]
https://github.com/prebid/professor-prebid/pull/29/files#r937905500

**Comment by florianerl** [comment]
hi @patmmccann , 

big sorry! I just published a new version. please let me know if this one is working for you now 🙏

**Comment by patmmccann** [comment]
confirming fixed, ty!!!
