### ISSUE TITLE
Professor Prebid is causing miro.com to be not useable

### ISSUE THREAD

**Issue by HannesAdevinta** [prebid/professor-prebid#36]
miro.com is not useable whenever the plug-in is turned on.
Don't know if other sites are affected as I had to turn it off.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/107627990/190990488-0b23461b-9c8f-421e-8069-ff4ac91a8a99.png">

**Comment by florianerl** [comment]
Hi @HannesAdevinta, 

thanks a lot for raising this. I pushed an update (v.0.2.49) to google webstore which fixes the issue for me: 
![image](https://user-images.githubusercontent.com/46747754/192743782-261268cc-4dcb-46ec-87bb-b35f7485c7c0.png)
would be great if you could confirm that it's working for you now.

**Comment by HannesAdevinta** [comment]
awesome that worked! this is sweet. thanks!

**Comment by florianerl** [comment]
happy to help :)
