### ISSUE TITLE
How to debug extension

### ISSUE THREAD

**Issue by oskarcokl** [prebid/professor-prebid#42]
Hello,
I'm trying to contribute to this project by fixing some of the issues I have observed (prebid styling in debug mode even when it is disabled in the extensions, and ad units disappearing on googletag.pubads.refresh() call), but I find it hard to debug the project and get a sense of what is going on.

I forked the repository and cloned it on my machine. Then build or "ran" it with "npm install" and "npm start". Then I "Loaded unpacked extension" as described in the README.md file. 

I then tried to to ad a "debugger;" statement so that I could step through the code, but the program never stopped. Then I tried adding some simple "console.log()" to see if it would work. But the logs never got called even though I could see them in the source code if I inspected the extension.

So I'm asking if you could help me set up a proper development environment or workflow so that I can understand the extension better and hopefully contribute some changes/fixes.

Thanks in advance for your reply.

**Comment by florianerl** [comment]
Hi @oskarcokl , 

i use chromes dev-tools: 

To debug the popup i right-click in the pop-up-window and select "inspect":

![image](https://user-images.githubusercontent.com/46747754/194259780-ebfa3992-6d69-4307-9006-d33762159e1c.png)
![image](https://user-images.githubusercontent.com/46747754/194259949-9842ea06-7286-4dbb-a26e-eaca784544f4.png)

To debug everything that's going on in the opened page itself you can use the pages dev-tools: 

![image](https://user-images.githubusercontent.com/46747754/194261042-fb0480e6-7ef5-484c-9282-8e9a255654be.png)
![image](https://user-images.githubusercontent.com/46747754/194261256-50fddd80-bc90-48cb-a4a5-d12b2953a64c.png)

To debug the background worker and content-script click here: 

![image](https://user-images.githubusercontent.com/46747754/194261673-f41df0a1-7ff4-4818-9a63-d93383b5db7e.png)


I hope that helps a bit and I'm looking forward to merge your PRs! 😃 
Please let me know in case you have further questions.

**Comment by oskarcokl** [comment]
Hi @florianerl thank you for you insightful answer,

I was able to debug the script that gets injected onto the page but I'm still having issues with getting console.logs to work inside components in the extension itself.

![Screenshot 2022-10-17 at 10 47 00](https://user-images.githubusercontent.com/32930687/196133115-567dbfa8-69ae-44a6-b622-4b8f1ff020f8.png)

I added a console.log inside the DebuggingModuleComponent.tsx so that I could get a better sense of some variables but I can't get it to actually print anything to the extension console.

![Screenshot 2022-10-17 at 10 47 34](https://user-images.githubusercontent.com/32930687/196133317-64dd2023-37b9-4a22-94fc-77fb44288edd.png)

Am I missing something with how the components get built? Am I not getting something with React? I can see the console log inside the code under the source tab but it just doesn't seem to work.

Thank you in advance for any further answers

**Comment by florianerl** [comment]
Hi @oskarcokl , 

your screenshots look a little bit like you were editing the comiled js files. Try editing the *.tsx files and launch a dev server instead: 
![image](https://user-images.githubusercontent.com/46747754/200828545-b76a27b0-8431-4343-aba8-8832aa3b0ca3.png)
Then click "load unpacked" to install the dev build
