### ISSUE TITLE
plugin doesn´t work anymore

### ISSUE THREAD

**Issue by monschyhh** [prebid/professor-prebid#43]
hi all, unfortunately my great chrome plugin doesn't work anymore. i work with a prebid wrapper and we had a problem with the prebid version. it had to be updated but is now back to the previous state. Unfortunately, my plugin now no longer works, it loads very, very briefly and then closes again.
i have already deleted cookies, reinstalled, unfortunately nothing helped. on other sites the tool works, only on the sites i work with, unfortunately not. does anyone have a tip? the company of the wrapper unfortunately has no more for me and i would be very happy. thank you in advance.

**Comment by florianerl** [comment]
hi @monschyhh , 

could you please share a url to a page where i can reproduce the issue?

**Comment by monschyhh** [comment]
hi florianerl,
yeah - e.g. comunio.de or kicktipp.de. thanks a lot in advance

**Comment by florianerl** [comment]
Hi @monschyhh , 

i pushed an update to version 2.50 today. With this version, i don't have any issues on those pages. Can you confirm it works for you too?

**Comment by monschyhh** [comment]
hi florianerl,
this looks great and work perfect!! thanks a lot:))

**Comment by florianerl** [comment]
very welcome :)
