### ISSUE TITLE
StorageAccess for adapters is undefined when standard: true

### ISSUE THREAD

**Issue by erezbens** [prebid/professor-prebid#49]
[According to the docs](https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html#2-bidder-setting-attributes:~:text=The%20basic%20structure%20is%20a%20%E2%80%98standard%E2%80%99%20section%20with%20defaults%20for%20all%20adapters%2C%20and%20then%20one%20or%20more%20adapter%2Dspecific%20sections%20that%20override%20behavior%20for%20that%20bidder), `standard: true` in `bidderSettings` allows storage access to all adapters. In the config panel, under Bidder Settings, storage access lists all adapters with their own setting (the explicit assignment to each one or undefined otherwise). This is misleading because access is granted globally.
Maybe we can show that access is allowed if `standard: true` exists, or at least put a side note for this?

**Comment by erezbens** [comment]
Thanks for the reply! 
Here is an example of a bidderSettings config 
![Screen Shot 2023-01-10 at 15 14 15](https://user-images.githubusercontent.com/52387483/211561341-e3a825d7-9c88-4298-852f-31cff3538127.png)
You can see here that `standard: true`, nonetheless storage access is evaluated to `undefined` for all the adapters.
It is true that they were not explicitly configured with `storageAllowed: true`, but they **can** access local storage.

You can watch it [here](https://unpasted.com/celebrities/justin-biebers-shades/).

**Comment by florianerl** [comment]
Hi @erezbens , 

i just pushed version 0.2.55 to chromes webstore that should fix your issue. please let me know if that works for you.

**Comment by erezbens** [comment]
hi @florianerl thanks for the quick action, that’s great!
