### ISSUE TITLE
Missing bidders in the AdUnits tab when setting up multiple adunits with the same code

### ISSUE THREAD

**Issue by aanton** [prebid/professor-prebid#55]
Hi,

In the AdUnits tab the bidders information is uncomplete when multiple adunits objects are set with the same code. Only one of them is shown in the bidders column. In the Bids tab all the the bidders are correctly shown.

Just an example of two adunits objects with the same code:

```js
[
  {
    code: "Top",
    bids: [
      {
        bidder: "appnexus",
        params: {
          placementId: 123456,
        },
      },
    ],
    mediaTypes: {
      banner: {
        sizes: [
          [970, 90],
          [970, 250],
        ],
      },
    },
  },
  {
    code: "Top",
    bids: [
      {
        bidder: "richaudience",
        params: {
          supplyType: "site",
          pid: "XYZ",
        },
      },
    ],
    mediaTypes: {
      banner: {
        sizes: [
          [970, 90],
          [970, 250],
          [1, 1],
        ],
      },
    },
  },
]
```

In this example two different adunits are set because the banner sizes must be different for each bidder.

Regards,
Armando

**Comment by aanton** [comment]
I share a fake site to test it:
https://professor-prebid-issue-55.netlify.app/?pbjs_debug=true

The AdUnits tab (only one bidder is shown):
![image](https://user-images.githubusercontent.com/717192/217895344-3d65a277-00b7-42a1-92b8-4885a2ae543d.png)

The Bids tab:
![image](https://user-images.githubusercontent.com/717192/217895469-0e68e1d8-a98a-4928-8944-de2e34311034.png)

It is just an example without a CMP and fake data.

**Comment by florianerl** [comment]
HI @aanton , 

thanks for your feedback! I published a new version today. Please let me know if that fixes your issues.

**Comment by aanton** [comment]
Hi @florianerl,

it works perfectly :+1: 

I have checked it in [the test page](https://professor-prebid-issue-55.netlify.app/?pbjs_debug=true). It uses five different AdUnits objects and all of them are reported correctly in the AdUnits tab.
![image](https://user-images.githubusercontent.com/717192/218819351-69d06783-7b23-4ad7-8518-286b34a719db.png)

Thanks!
