### ISSUE TITLE
Extension breaks when using sizeMappingV2 module

### ISSUE THREAD

**Issue by piyush33patel** [prebid/professor-prebid#57]
I have noticed that the extension breaks and collapses on pages that are using [sizeMappingV2](https://docs.prebid.org/dev-docs/modules/sizeMappingV2.html)
Though I am not sure if this is the only reason, can someone confirm?

**Comment by florianerl** [comment]
hi @piyush33patel , 

could you provide a url to a page where i can reproduce your issue?

**Comment by florianerl** [comment]
🤔  which version of the extension are you running? 

![image](https://user-images.githubusercontent.com/46747754/223148070-5c8b1792-70f6-463f-8cbe-61471ad5eb15.png)

![image](https://user-images.githubusercontent.com/46747754/223148480-307e0ac8-f5a2-40cd-a314-b8ae1f82e7bb.png)

**Comment by piyush33patel** [comment]
Even I am using the same
<img width="691" alt="image" src="https://user-images.githubusercontent.com/56225984/223148991-3d9aa4d0-1ac1-4ceb-bc08-6af22b3d7c18.png">
Honestly, after I send you the link, the extension worked fine for few pages. Now again it breaks. I am unable to find under what circumstances it is crashing.

**Comment by florianerl** [comment]
Hi @piyush33patel , 

i just pushed an update (v 0.2.58) that should fix your issue. It will be available in a few hours after google has reviewed the changes.

**Comment by florianerl** [comment]
Hi @florianerl , 

has your issue been resolved? Can i close this?
