### ISSUE TITLE
Lodash is being injected to window._

### ISSUE THREAD

**Issue by JSzychulec** [prebid/professor-prebid#59]
Changes made in #58 are causing lodash to replace global `_` property, rendering some websites unable to load due to them relying on underscore under aforementioned `_` in global window.

https://github.com/prebid/professor-prebid/blob/f071e15ded0e5c5efef5c5e143fafcf0fed06b1a/src/inject/scripts/prebid.ts#L3

It seems like importing isArray like this instead: `import isArray from 'lodash/isArray';` should resolve this issue.

**Comment by florianerl** [comment]
Hi @JSzychulec , 

thanks for your feedback i just published version 0.2.59 in which i removed lodash from that file and use Array.isArray() instead.
