### ISSUE TITLE
Ad gam query id to the overlay

### ISSUE THREAD

**Issue by patmmccann** [prebid/professor-prebid#6]
If one opens the google console, the query id and the associated link are really convenient. Rather than opening two overlays, it would be really helpful if it was in our overlay as well, when gam is the ad server.

**Comment by patmmccann** [comment]
@florianerl the gam query id is not in that screenshout

**Comment by patmmccann** [comment]
here is a goofc screenshot with the query id 
![image](https://user-images.githubusercontent.com/1683175/171675186-e1360c71-0ee9-4557-8050-d78ad490ee02.png)

it should link to 
`
https://admanager.google.com/[NETWORKCODE]#troubleshooting/screenshot/query_id=[QUERYID]
eg
https://admanager.google.com/18190176#troubleshooting/screenshot/query_id=CPSJtqiTj_gCFZbqhwodgSIKpw
`

**Comment by florianerl** [comment]
done: 
![image](https://user-images.githubusercontent.com/46747754/174019384-3d379ed8-2027-462e-926a-3c2be2ca350b.png)

**Comment by patmmccann** [comment]
Awesome!!
