### ISSUE TITLE
Extension timeout too short

### ISSUE THREAD

**Issue by jonasbraga** [prebid/professor-prebid#61]
Hello, I was facing an issue with the plugin that the 8 seconds timeout (https://github.com/prebid/professor-prebid/blob/master/src/inject/scripts/prebid.ts#L151) is not enough in my case (https://empire.goodgamestudios.com/ - only lvl10+ players see ads)

I've cloned de repo locally and changed this to 60 seconds (a lot but since it's just listening and waiting until prebid scripts are available, I don't think it would lead to any performance issues), and it fixed the problem

So, I would like to inform you of that, and also know your thoughts about it
Should we change, keep, or maybe add a new dynamic selection to this timeout value?

Once we agree in a solution I can create the PR for you as well

thx

**Comment by florianerl** [comment]
Hi @jonasbraga , 

thanks for your feedback! I think the best way to go would be to add a dynamic selection. 
I'm currently about to leave for vacation, so please have some patience with me. 
I'd also be happy to merge a PR from you
