### ISSUE TITLE
unable to install due to fontawesome dependency errors

### ISSUE THREAD

**Issue by ybootin** [prebid/professor-prebid#7]
Hi

First, thanks for providing this extension.

i've tryed to build and install the extension following the readme, but i faced an issue with fontawesome
```
ERROR in ./node_modules/@fortawesome/react-fontawesome/index.es.js 1:0-64
Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/Users/yohan/Projects/sandbox/professor-prebid/node_modules/@fortawesome/react-fontawesome'
resolve '@fortawesome/fontawesome-svg-core' in '/Users/yohan/Projects/sandbox/professor-prebid/node_modules/@fortawesome/react-fontawesome'
```

I've tryed manual install of `fontawesome-svg-core` , by doing this 
```
npm i --save @fortawesome/fontawesome-svg-core
```

but it come with others errors now.

i'm using node `v14.17.4`

try a build on a fresh install to reproduce (clone, npm install, npm start)

Thanks

**Comment by florianerl** [comment]
Hi, 

thanks for your feedback!
Did you run `npm install` before trying to build it? Fontawesome is listed as dependency in [package.json](https://github.com/prebid/professor-prebid/blob/77ac047311353aaff4274542e56faa4b5512f09f/package.json#L19). 
In case you just want to download the extension, it's also available in chrome's web-store: https://chrome.google.com/webstore/detail/professor-prebid-v02/kdnllijdimhbledmfdbljampcdphcbdc

**Comment by ybootin** [comment]
Hi @florianerl , thanks for your answer

yes i've followed the readme : 
```
git clone git@github.com:prebid/professor-prebid.git
cd professor-prebid
npm install
npm start
```

I'm on Mac OSX 10.15.7

you can try out using a fresh docker install to solve the dependency issue

**Comment by florianerl** [comment]
Hi @ybootin , 

i removed the fontawesome dependency. It was just for only 1 Google Logo anyways.
