### ISSUE TITLE
Extension does not work if pbjs object is named differently ?

### ISSUE THREAD

**Issue by mukero320** [prebid/professor-prebid#82]
HIt seems that on wprost.pl I can't see anything related to prebid with this extension. We use "genesisAds" instead of "pbjs". Should it work with changed name ? If not, is there a way for what object does this extension look for ?

**Comment by florianerl** [comment]
Hi @mukero320 , 

the extensions checks window._pbjsGlobals for prebid instances on the page. As far as I can see on www.wprost.pl _pbjsGlobals is null: 
![image](https://github.com/prebid/professor-prebid/assets/46747754/cb5696b4-25cc-4223-a04e-0379a58c80ed)
