### ISSUE TITLE
extension has blinking configs

### ISSUE THREAD

**Issue by Andrii-Pavlenko** [prebid/professor-prebid#86]
We have n issue with `UserIds` in the config. First it is empty. Then it gets some content. Then the content disappears. Then we have content again and then it disappears again. 

In our logic we have all config after loading and then it does not change.

Please have a look in attached video

https://github.com/prebid/professor-prebid/assets/53989171/0db31631-8572-405a-9ed8-c54b89cf93d0

**Comment by florianerl** [comment]
HI @Andrii-Pavlenko , 

could you please provide a url of the page where you experience this issue?

**Comment by Andrii-Pavlenko** [comment]
Hi @florianerl,
you can try it on [this](https://www.usnews.com/) page. You should also be use VPN to the USA to reproduce it, if you are not located overe there.

**Comment by florianerl** [comment]
Hi @Andrii-Pavlenko ,

big sorry for the long radio silence! 
Could you please let me know if version 0.2.73 fixes your issue?
![AF4F7CD2-E0EA-4397-AD16-68E741B27BA7-716-00005B89F1C1771E](https://github.com/prebid/professor-prebid/assets/46747754/6489ec34-7454-4971-a0bb-cbae1a38ab26)
