### ISSUE TITLE
Request: Within the Input to a bidder, display TOPICS and ORTB2 object passed to the bidder

### ISSUE THREAD

**Issue by pm-harshad-mane** [prebid/professor-prebid#89]
<img width="804" alt="Screenshot 2024-04-16 at 4 11 54 PM" src="https://github.com/prebid/professor-prebid/assets/8835908/81702229-0c63-4776-be36-3b1d4e451a80">

**In the above screen-shot, when user clicks on a bidder's name, you can see what was the input to the bidder, as below**

<img width="361" alt="Screenshot 2024-04-16 at 4 11 43 PM" src="https://github.com/prebid/professor-prebid/assets/8835908/6b9ae5ff-70b1-4340-81ed-105ce550f3de">

**Can we show TOPICS and ORTB2 object passed as an input to the bidder ?**

**Also, In Timeline view (screen-shot) below, there are some more fields populated that are inputs... can we add TOPICS information here as well? And keep the views consistent?**

<img width="802" alt="Screenshot 2024-04-16 at 4 14 09 PM" src="https://github.com/prebid/professor-prebid/assets/8835908/d7777cb6-7c34-44b6-99bb-79c0d64d2210">

**Actually it will be very helpful if we could show the bidder request sent by the bidder, that will tell whether a particular input was consumed by the bidder or not.**

**Comment by jlquaccia** [comment]
Just opened up a PR for this ticket.  @florianerl @pm-harshad-mane could you review?  Thanks!
