### ISSUE TITLE
Doesn't find Prebid with different Global

### ISSUE THREAD

**Issue by spormeon** [prebid/professor-prebid#9]
We use a different glaobal for prebid and the extension doesnt seem to pick it up.  Either that or it doesnt like Video prebid?

**Comment by florianerl** [comment]
Hi @spormeon , 

could you please share your page on which prebid is not detected? 
Is your global listed in `_pbjsGlobals`?

**Comment by spormeon** [comment]
in or as?

**Comment by patmmccann** [comment]
@spormeon would you expect the function at https://github.com/prebid/Prebid.js/blob/master/src/prebidGlobal.js to work?

**Comment by spormeon** [comment]
is that tied to pbjs, as our global is set at adyjs ?

**Comment by allanjun** [comment]
hi, 
The extension is able to detect and handle different prebid instances running on the page. It reads window._pbjsGlobals: 
https://github.com/prebid/professor-prebid/blob/a43d82d6ffb9aed497d9477c9c81de72045bd506/src/inject/scripts/prebid.ts#L139

maybe there is a limitation if your wrapper is embeded into an iframe, in that case I'm not entirely sure if we can make it search for this global presence on all frame documents on the page, any thoughts @florianerl  ?

**Comment by spormeon** [comment]
but this presumes that the "global" is pbjs?
![DevTools_-_cdn_adysis_com_VideoDemo_videofloat_html](https://user-images.githubusercontent.com/8503167/169544212-fb3436ae-7f30-41bf-bdde-b782c5fc6651.png)

**Comment by florianerl** [comment]
Hi @spormeon ,

you are not supposed to rename `window._pbjsGlobals` to `window._adyjsGlobals`. In your case it should look like this
![image](https://user-images.githubusercontent.com/46747754/170450740-73c046ae-434d-41bd-9a10-f1d26353b744.png)
or in case there are more prebid instances running in you page: 
![image](https://user-images.githubusercontent.com/46747754/170451125-ef34e815-4187-4358-bdf7-b2ccfd3847a5.png)

**Comment by spormeon** [comment]
ye, went through that with Allan on slack chat, I changed it and it still dont work

**Comment by florianerl** [comment]
Would you mind sharing a (test-)page where we can reproduce your issue?

**Comment by spormeon** [comment]
are you on the slack adops, rather give that info in DM's etc
