### ISSUE TITLE
Help with Prebid Timing

### ISSUE THREAD

**Issue by simplo** [prebid/professor-prebid#99]
## Type of issue
It seems my page pushes banners befor Prebid ended, but no timeout.

## Description
I'm using professor prebid to check the bids, but I get banners before prof displays the bids, even if the system is not in timeout.
Is there a way to understand the status od the bids and check if the result has been sent to the system?

## Steps to reproduce
just connect to https://www.tiscali.it/services/vee.html and check when banners are displayed while checking bids sith professor prebid

## Test page
(https://www.tiscali.it/services/vee.html)

### Expected results
Banners displays after bidding is over or after timeout

### Actual results
It seems banners are displayed before the bids are sent

## Platform details
Any browser.
We are using prebid8.51.0

**Comment by simplo** [comment]
Thank you guys!

**Comment by florianerl** [comment]
Hi @simplo , 

could you please check if vesion 0.2.73 (published 24th of June '24) fixes your issue? 
Many thanks in advance!

**Comment by simplo** [comment]
Hi, I'm trying it since 2 days, it seems fixed.
Thank you!
